local TIME = require("main/modules/time")

function init(self)
	msg.post(".", "acquire_input_focus")
end


function update(self, dt)
	
end

function on_message(self, message_id, message, sender)
	
end

function on_input(self, action_id, action)
	if action.pressed and action_id == hash("debug1") then
		TIME.stop()
	elseif action.pressed and action_id == hash("debug2") then
		TIME.start()
	elseif action.pressed and action_id == hash("debug3") then
		
	end
end
