local screen_size = {x = 1280, y = 900}
local active_button
local mouse_pressed = false

function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") then
		if message.other_group == hash("button") then
			if message.enter then
				active_button = message.other_id
				if mouse_pressed then msg.post(active_button, "pressed") end
			else
				msg.post(message.other_id, "released")
				if active_button == message.other_id then active_button = nil end
			end
		end
	elseif message_id == hash("deleted") then
		if active_button == message.id then active_button = nil end
	end
end

function on_input(self, action_id, action)
	local zoom = math.min(screen_size.x / 1280, screen_size.y / 900)
	local projected_width = screen_size.x / zoom
	local projected_height = screen_size.y / zoom
	local xoffset = -(projected_width - 1280) / 2
	local yoffset = -(projected_height - 900) / 2
	local x = (action.x / 1280) * projected_width + xoffset
	local y = (action.y / 900) * projected_height + yoffset
	go.set_position(vmath.vector3(x, y, 1), go.get_id("/cursor"))
	if action_id == hash("click") then
		if action.pressed then
			mouse_pressed = true
			if active_button then msg.post(active_button, "pressed") end
		elseif action.released then
			mouse_pressed = false
			if active_button then
				msg.post(active_button, "activated")
			end
		end
	end
end